const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '../.env') });

const Event = require('../models/Event');
const User = require('../models/User');
const Registration = require('../models/Registration');

const events = [
  {
    name: 'React & Next.js Summit 2025',
    organizer: 'TechConf India',
    location: 'Hyderabad',
    date: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000 + 8 * 60 * 60 * 1000),
    description: 'Join the biggest React & Next.js conference in South Asia. Learn from industry experts, discover the latest features, and network with thousands of developers. Featuring workshops, live demos, and Q&A sessions.',
    capacity: 500,
    availableSeats: 342,
    category: 'Technology',
    tags: ['React', 'Next.js', 'JavaScript', 'Frontend'],
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=800',
    price: 999,
    isFeatured: true,
  },
  {
    name: 'AI & Machine Learning Workshop',
    organizer: 'DataSci Hub',
    location: 'Bangalore',
    date: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000),
    endDate: new Date(Date.now() + 14 * 24 * 60 * 60 * 1000 + 6 * 60 * 60 * 1000),
    description: 'A hands-on workshop covering the fundamentals of AI and Machine Learning. Work with real datasets, build predictive models, and understand neural networks from scratch. Suitable for beginners to intermediate developers.',
    capacity: 100,
    availableSeats: 23,
    category: 'Technology',
    tags: ['AI', 'ML', 'Python', 'TensorFlow'],
    imageUrl: 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?w=800',
    price: 1499,
    isFeatured: true,
  },
  {
    name: 'Bollywood Night 2025',
    organizer: 'Event Masters',
    location: 'Mumbai',
    date: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000),
    description: 'Experience the magic of Bollywood live! Featuring top Bollywood artists, stunning performances, and an unforgettable night of music and dance. Don\'t miss the biggest entertainment event of the year!',
    capacity: 2000,
    availableSeats: 756,
    category: 'Music',
    tags: ['Bollywood', 'Music', 'Dance', 'Entertainment'],
    imageUrl: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?w=800',
    price: 799,
    isFeatured: true,
  },
  {
    name: 'IPL Fan Fest Hyderabad',
    organizer: 'Sports Events Co.',
    location: 'Hyderabad',
    date: new Date(Date.now() + 21 * 24 * 60 * 60 * 1000),
    description: 'Celebrate the spirit of cricket at the IPL Fan Fest! Watch live matches on giant screens, meet cricket legends, participate in contests, and enjoy food & entertainment. A must-attend for cricket fans!',
    capacity: 5000,
    availableSeats: 1234,
    category: 'Sports',
    tags: ['Cricket', 'IPL', 'Sports', 'Fan Fest'],
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=800',
    price: 299,
    isFeatured: false,
  },
  {
    name: 'Startup India Conclave',
    organizer: 'Nasscom Foundation',
    location: 'Delhi',
    date: new Date(Date.now() + 10 * 24 * 60 * 60 * 1000),
    description: 'Connect with 500+ startup founders, investors, and mentors. Pitch your startup, attend masterclasses, and explore funding opportunities. The premier startup networking event in India.',
    capacity: 600,
    availableSeats: 89,
    category: 'Business',
    tags: ['Startup', 'Networking', 'Investment', 'Entrepreneurship'],
    imageUrl: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800',
    price: 1999,
    isFeatured: true,
  },
  {
    name: 'Digital Art & NFT Expo',
    organizer: 'Creative Minds Gallery',
    location: 'Pune',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    description: 'Explore the intersection of art and blockchain technology. Meet digital artists, discover NFT collections, attend minting workshops, and understand the future of digital ownership and creativity.',
    capacity: 300,
    availableSeats: 167,
    category: 'Art',
    tags: ['NFT', 'Digital Art', 'Blockchain', 'Creative'],
    imageUrl: 'https://images.unsplash.com/photo-1547826039-bfc35e0f1ea8?w=800',
    price: 599,
    isFeatured: false,
  },
  {
    name: 'Masala Food Festival',
    organizer: 'Gourmet India',
    location: 'Chennai',
    date: new Date(Date.now() + 4 * 24 * 60 * 60 * 1000),
    description: 'A celebration of Indian cuisine featuring 100+ food stalls, celebrity chef demonstrations, cooking competitions, and regional delicacies from across India. A paradise for food lovers!',
    capacity: 3000,
    availableSeats: 2145,
    category: 'Food',
    tags: ['Food', 'Cuisine', 'Chef', 'Culture'],
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    price: 199,
    isFeatured: false,
  },
  {
    name: 'Yoga & Mindfulness Retreat',
    organizer: 'Wellness India',
    location: 'Rishikesh',
    date: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    description: 'A 2-day immersive yoga and mindfulness retreat on the banks of the Ganges. Includes meditation sessions, pranayama workshops, organic meals, and sessions by internationally certified yoga instructors.',
    capacity: 50,
    availableSeats: 12,
    category: 'Health',
    tags: ['Yoga', 'Meditation', 'Wellness', 'Mindfulness'],
    imageUrl: 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=800',
    price: 3999,
    isFeatured: false,
  },
  {
    name: 'Python & Django Bootcamp',
    organizer: 'Code Academy',
    location: 'Bangalore',
    date: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    description: 'Intensive 3-day bootcamp covering Python fundamentals, Django framework, REST APIs, and deployment. Build real-world projects and get placement assistance. Suitable for beginners with no prior programming experience.',
    capacity: 80,
    availableSeats: 45,
    category: 'Education',
    tags: ['Python', 'Django', 'Backend', 'Programming'],
    imageUrl: 'https://images.unsplash.com/photo-1461749280684-dccba630e2f6?w=800',
    price: 2499,
    isFeatured: false,
  },
  {
    name: 'Stand-Up Comedy Nights',
    organizer: 'LOL Productions',
    location: 'Mumbai',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    description: 'A night of laughter featuring India\'s top stand-up comedians. Enjoy 3 hours of non-stop comedy, open mic sessions, and exclusive meet-and-greet opportunities. Perfect for unwinding after a long week!',
    capacity: 400,
    availableSeats: 234,
    category: 'Entertainment',
    tags: ['Comedy', 'Stand-Up', 'Humor', 'Live Show'],
    imageUrl: 'https://images.unsplash.com/photo-1527224857830-43a7acc85260?w=800',
    price: 499,
    isFeatured: false,
  },
  {
    name: 'Cloud Computing Summit',
    organizer: 'AWS India',
    location: 'Hyderabad',
    date: new Date(Date.now() + 18 * 24 * 60 * 60 * 1000),
    description: 'The premier cloud computing conference covering AWS, Azure, and GCP. Sessions on serverless architecture, Kubernetes, DevOps, and cloud security. Over 50 technical sessions and hands-on labs.',
    capacity: 800,
    availableSeats: 312,
    category: 'Technology',
    tags: ['Cloud', 'AWS', 'DevOps', 'Kubernetes'],
    imageUrl: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800',
    price: 1299,
    isFeatured: false,
  },
  {
    name: 'Marathon for a Cause',
    organizer: 'Run India',
    location: 'Delhi',
    date: new Date(Date.now() + 12 * 24 * 60 * 60 * 1000),
    description: 'Annual charity marathon with 5K, 10K, and 21K runs. All proceeds go to education for underprivileged children. Join thousands of runners, get finisher medals, and make a difference!',
    capacity: 10000,
    availableSeats: 6789,
    category: 'Sports',
    tags: ['Marathon', 'Running', 'Charity', 'Fitness'],
    imageUrl: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?w=800',
    price: 399,
    isFeatured: false,
  },
  {
    name: 'Women in Tech Conference',
    organizer: 'She Codes',
    location: 'Bangalore',
    date: new Date(Date.now() + 22 * 24 * 60 * 60 * 1000),
    description: 'Empowering women in technology through keynotes, panel discussions, networking, and mentorship sessions. Featuring inspiring stories from top women leaders in tech. Open to all genders.',
    capacity: 400,
    availableSeats: 178,
    category: 'Technology',
    tags: ['Women', 'Tech', 'Leadership', 'Diversity'],
    imageUrl: 'https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?w=800',
    price: 699,
    isFeatured: true,
  },
  {
    name: 'Photography Masterclass',
    organizer: 'Lens & Light Studio',
    location: 'Jaipur',
    date: new Date(Date.now() + 8 * 24 * 60 * 60 * 1000),
    description: 'Two-day photography masterclass covering composition, lighting, portrait photography, landscape shooting, and post-processing in Lightroom. All skill levels welcome. Bring your DSLR or mirrorless camera.',
    capacity: 30,
    availableSeats: 8,
    category: 'Art',
    tags: ['Photography', 'Lightroom', 'Creative', 'Workshop'],
    imageUrl: 'https://images.unsplash.com/photo-1452780212940-6f5c0d14d848?w=800',
    price: 3499,
    isFeatured: false,
  },
  {
    name: 'BlockChain & Web3 Expo',
    organizer: 'Crypto India',
    location: 'Mumbai',
    date: new Date(Date.now() + 25 * 24 * 60 * 60 * 1000),
    description: 'Dive into the world of Web3, DeFi, and Blockchain technology. Learn about smart contracts, DAOs, crypto regulations, and the future of decentralized internet. Expert talks and networking with blockchain pioneers.',
    capacity: 600,
    availableSeats: 423,
    category: 'Technology',
    tags: ['Blockchain', 'Web3', 'Crypto', 'DeFi'],
    imageUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=800',
    price: 899,
    isFeatured: false,
  },
  {
    name: 'Mental Health Awareness Walk',
    organizer: 'Mind Matters NGO',
    location: 'Chennai',
    date: new Date(Date.now() + 6 * 24 * 60 * 60 * 1000),
    description: 'A community walk to raise awareness about mental health. Featuring talks by therapists, mindfulness sessions, and resources for mental health support. Free event open to all. Together, let\'s break the stigma.',
    capacity: 1000,
    availableSeats: 934,
    category: 'Health',
    tags: ['Mental Health', 'Awareness', 'Community', 'Free'],
    imageUrl: 'https://images.unsplash.com/photo-1559521783-1d1599583485?w=800',
    price: 0,
    isFeatured: false,
  },
  {
    name: 'E-commerce Growth Summit',
    organizer: 'Digital Business India',
    location: 'Pune',
    date: new Date(Date.now() + 16 * 24 * 60 * 60 * 1000),
    description: 'Learn growth strategies from e-commerce veterans. Topics include SEO, paid advertising, conversion optimization, supply chain, and scaling to 100Cr+ ARR. Exclusive case studies from top Indian e-commerce brands.',
    capacity: 350,
    availableSeats: 203,
    category: 'Business',
    tags: ['E-commerce', 'Growth', 'Marketing', 'Business'],
    imageUrl: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800',
    price: 1799,
    isFeatured: false,
  },
  {
    name: 'Jazz & Blues Music Festival',
    organizer: 'Music Republic',
    location: 'Bangalore',
    date: new Date(Date.now() + 9 * 24 * 60 * 60 * 1000),
    description: 'Three days of soul-stirring jazz and blues music featuring international and Indian artists. Set in the beautiful grounds of Lal Bagh, this outdoor festival promises an unforgettable musical journey.',
    capacity: 1500,
    availableSeats: 876,
    category: 'Music',
    tags: ['Jazz', 'Blues', 'Outdoor', 'Festival'],
    imageUrl: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=800',
    price: 649,
    isFeatured: false,
  },
  {
    name: 'Data Science & Analytics Conference',
    organizer: 'Analytics Vidhya',
    location: 'Hyderabad',
    date: new Date(Date.now() + 20 * 24 * 60 * 60 * 1000),
    description: 'India\'s largest data science conference featuring 60+ sessions on data engineering, analytics, BI tools, and data-driven decision making. Meet data scientists from top companies and explore career opportunities.',
    capacity: 1000,
    availableSeats: 567,
    category: 'Technology',
    tags: ['Data Science', 'Analytics', 'BI', 'Statistics'],
    imageUrl: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    price: 1199,
    isFeatured: false,
  },
  {
    name: 'Kids Science & Robotics Fair',
    organizer: 'STEM Foundation India',
    location: 'Delhi',
    date: new Date(Date.now() + 11 * 24 * 60 * 60 * 1000),
    description: 'An interactive science and robotics fair for children aged 6-16. Hands-on experiments, robot building workshops, coding sessions, and science demonstrations. Spark curiosity and creativity in young minds!',
    capacity: 500,
    availableSeats: 289,
    category: 'Education',
    tags: ['Kids', 'STEM', 'Robotics', 'Science'],
    imageUrl: 'https://images.unsplash.com/photo-1485546246426-74dc88dec4d9?w=800',
    price: 349,
    isFeatured: false,
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('✅ Connected to MongoDB');

    // Clear existing data
    await Event.deleteMany({});
    await Registration.deleteMany({});
    console.log('🗑️  Cleared existing events and registrations');

    // Insert events
    const createdEvents = await Event.insertMany(events);
    console.log(`✅ Seeded ${createdEvents.length} events`);

    console.log('\n📊 Events Summary:');
    createdEvents.forEach((e) => {
      console.log(`  - ${e.name} | ${e.category} | ${e.location} | Seats: ${e.availableSeats}/${e.capacity}`);
    });

    console.log('\n✅ Database seeded successfully!');
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding error:', error);
    process.exit(1);
  }
};

seedDatabase();
